baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = ""
theme         = "roxo-hugoz"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = ""
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Über uns"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Kontakt"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  dateFormat = "26 FEB 1994"
  # Meta data
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/ZMeKa3L"
[params.stripe]
publishableKey = "pk_live_51Lxm6sEgtx1au46GHhDtjk3JZ04OaA8p7T6xM4lQFLxfbPotRsuT4AhoM4WA0myCsirZeQN32vnUvUSmn1zVyD3m00docojbx7"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Name"
    placeholder_last_name         = "Nachname"
    placeholder_email             = "Email"
    placeholder_project_type      = "Art der Frage"
    placeholder_about_the_project = "Beschreibung"
    send_message                  = "Schicken"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Individuelle Modellierung"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Allgemein"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/headerimg.png"
    heading               = "Bequemer & schneller Druckservice mit individueller Modellerstellung"
    tagline               = "Was möchten Sie heute ausdrucken?"
    primary_button        = "Beispiele"
    primary_button_url    = "portfolio"
    secondary_button      = "Kontakt"
    secondary_button_url  = "contact"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "3DPrintWien.at"
      address = "Vorgartenstrasse 171, Wien"
      email   = "majer@ermine.de"
      # Footer Sitemap
  
 
      # Footer Service
      [params.footer.service]
        title       = "Über uns:"
        description = "Ein persönliches Projekt, entstanden aus einem eigenen Problem: Hohe Preise anderer Unternehmen oder Schwierigkeiten haben, den Auftrag überhaupt drucken zu lassen."